apiVersion: v1
clusters:
- cluster:
    server: https://13.52.177.59:16443
    insecure-skip-tls-verify: true
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: bmlKbGVsTW01czFuY2o1YzZIdXRURzRtMVR0WnlxdERmZ2xUamJrQ254Yz0K