name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade mozart-es --install --wait --atomic --namespace=default -f=./hysds/mozart/elasticsearch/values-override.yml
          kubeconfig: '${{ secrets.KUBECONFIG }}'
